// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wallet balances in satoshis.
 */
export type Balances = { onchain_total_sat: string, onchain_spendable_sat: string, anchor_reserve_sat: string, lightning_sat: string, };
