// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChannelView = { channel_id: string, 
/**
 * Our own id for the channel (a u128 in decimal); closing a channel needs it.
 */
user_channel_id: string, counterparty_node_id: string, 
/**
 * `txid:vout` of the funding output, once it exists.
 */
funding_txo: string | null, 
/**
 * `block x tx x output`, once the funding transaction is confirmed.
 */
short_channel_id: string | null, capacity_sat: string, 
/**
 * What we can send right now.
 */
outbound_msat: string, 
/**
 * What we can receive right now.
 */
inbound_msat: string, 
/**
 * The largest single payment this channel can carry now. Often well below `outbound_msat`:
 * the peer caps how much may be in flight (LDK's default is 10% of the channel).
 */
max_send_msat: string, is_outbound: boolean, is_channel_ready: boolean, is_usable: boolean, confirmations: number | null, confirmations_required: number | null, 
/**
 * Everything on our side of the channel, reserve included: what we would claim if it closed
 * now (before on-chain fees). None until the channel is confirmed.
 */
our_balance_sat: string | null, 
/**
 * What we must keep in the channel. It is part of our balance but cannot be spent.
 */
our_reserve_sat: string | null, 
/**
 * What the peer must keep in the channel. The first sats they receive fill it, so they do not
 * show up as spendable for them or as receivable for us.
 */
their_reserve_sat: string, };
