// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CheckId = "signature" | "expected_payee" | "expiry" | "network" | "amount" | "description_hash" | "required_fields" | "features" | "field_encoding" | "unknown_fields";
