// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecodedInvoice } from "./DecodedInvoice";
import type { RawField } from "./RawField";
import type { ValidationReport } from "./ValidationReport";

export type Decoded = { 
/**
 * The input after trimming, stripping `lightning:` and lowercasing. `RawField` offsets index into this.
 */
normalized: string, invoice: DecodedInvoice, report: ValidationReport, anatomy: Array<RawField>, };
