// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Network } from "./Network";

/**
 * Everything that is not inside the invoice: the current time and the caller's policy.
 */
export type DecodeContext = { now_unix: number, expected_network: Network | null, expected_payee: string | null, description_preimage: string | null, max_amount_msat: string | null, };
