// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Fatal errors: the input cannot be read as a BOLT11 invoice at all.
 *
 * Positions are character offsets into `Decoded::normalized` (the trimmed, lowercased input
 * without a `lightning:` prefix), so a UI can underline the exact spot.
 */
export type DecodeError = { "code": "missing_separator" } | { "code": "invalid_char", pos: number, ch: string, } | { "code": "mixed_case" } | { "code": "bad_checksum" } | { "code": "unknown_currency", prefix: string, } | { "code": "invalid_amount", amount: string, reason: string, } | { "code": "too_short" } | { "code": "field_overrun", tag: string, pos: number, } | { "code": "invalid_signature_encoding" } | { "code": "recovery_failed" };
