// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HexBytes } from "./HexBytes";

export type Fallback = { 
/**
 * 0 to 16 is a segwit version, 17 is P2PKH, 18 is P2SH.
 */
version: number, program: HexBytes, address: string, };
