// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KnownFeature } from "./KnownFeature";

export type Features = { 
/**
 * Set bit positions, lowest first.
 */
bits: Array<number>, known: Array<KnownFeature>, 
/**
 * Unknown even bits: "it's ok to be odd", so these make the invoice unpayable.
 */
unknown_required: Array<number>, unknown_optional: Array<number>, };
