// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FieldStatus = "parsed" | "duplicate" | "skipped_bad_length" | "invalid" | "unknown";
