// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Live node events, streamed to the browser over SSE.
 */
export type NodeEvent = { "kind": "payment_successful", payment_hash: string, fee_paid_msat: string | null, } | { "kind": "payment_failed", payment_hash: string | null, reason: string | null, } | { "kind": "payment_received", payment_hash: string, amount_msat: string, } | { "kind": "channel_pending", channel_id: string, counterparty_node_id: string, } | { "kind": "channel_ready", channel_id: string, counterparty_node_id: string | null, } | { "kind": "channel_closed", channel_id: string, reason: string | null, } | { "kind": "payments_changed" } | { "kind": "other", name: string, };
