// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Node state for the dashboard.
 */
export type NodeStatus = { node_id: string, network: string, is_running: boolean, block_height: number, best_block_hash: string, 
/**
 * False until both wallets have finished their first sync with bitcoind.
 */
is_synced: boolean, last_onchain_sync: number | null, last_lightning_sync: number | null, 
/**
 * Where peers can reach this node, as `host:port`.
 */
listening_addresses: Array<string>, };
