// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PayeeSource } from "./PayeeSource";

export type Payee = { pubkey: string, source: PayeeSource, };
