// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Direction } from "./Direction";
import type { PaymentKindView } from "./PaymentKindView";
import type { PaymentState } from "./PaymentState";

export type PaymentView = { id: string, kind: PaymentKindView, direction: Direction, status: PaymentState, amount_msat: string | null, fee_paid_msat: string | null, payment_hash: string | null, 
/**
 * Proof of payment. Only present once an outbound payment succeeded or an inbound one was claimed.
 */
preimage: string | null, txid: string | null, 
/**
 * When the last status change happened. Moves on every change, for example on confirmation.
 */
updated_at: number, 
/**
 * When this node first saw the payment. Fixed once recorded; payments that existed before the
 * node started tracking this carry their last update time as an estimate.
 */
first_seen_at: number, };
