// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PaymentKindView = "onchain" | "bolt11" | "bolt11_jit" | "bolt12_offer" | "bolt12_refund" | "spontaneous";
