// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PeerView = { node_id: string, address: string, is_connected: boolean, is_persisted: boolean, };
