// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldStatus } from "./FieldStatus";
import type { SegmentKind } from "./SegmentKind";

/**
 * One labelled slice of the normalized invoice string.
 */
export type RawField = { kind: SegmentKind, 
/**
 * The bech32 type character for tagged fields.
 */
tag: string | null, 
/**
 * Character offset into `Decoded::normalized`.
 */
start: number, raw: string, 
/**
 * Data length in 5-bit words, for tagged fields.
 */
len_words: number | null, status: FieldStatus, note: string | null, };
