// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SegmentKind = "hrp" | "separator" | "timestamp" | "tagged_field" | "signature" | "checksum";
