// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Check } from "./Check";
import type { Verdict } from "./Verdict";

export type ValidationReport = { verdict: Verdict, checks: Array<Check>, };
